export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const SET_TOOLBAR_TYPE_SUCCESS = 'SET_TOOLBAR_TYPE_SUCCESS';
export const SET_BOTTOM_TOOLBAR_TYPE_SUCCESS = 'SET_BOTTOM_TOOLBAR_TYPE_SUCCESS';
export const SORTBY_LOCATIONS_SUCCESS_BY_AZ = 'SORTBY_LOCATIONS_SUCCESS_BY_AZ';
export const SORTBY_LOCATIONS_SUCCESS_BY_DATE = 'SORTBY_LOCATIONS_SUCCESS_BY_DATE';